src/apps/analisis_clinicos/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from apps.analisis_clinicos import views
from rest_framework_jwt.views import obtain_jwt_token

app_name = 'analisis_clinicos'

urlpatterns = [
    path('', views.AnalisisView.as_view(),
         name='analisis_list'),
    path('resultados/', views.ResultadosView.as_view(),
         name='resultados_list'),
    path('nuevo/<int:analisis_id>/', views.NewAnalisisView.as_view(),
         name='nuevo_resultado'),
]

src/metrisalud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include(
        ('django.contrib.auth.urls', 'auth'),
        namespace='auth'
    )),

    path('users/', include('apps.usuario.urls', namespace='user')),
    path('', include('apps.web.urls', namespace='web')),

    path('analisis/', include(
        'apps.analisis_clinicos.urls', namespace='analisis'
    )),
]

src/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MetriSalud | {% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'bulma/css/bulma.min.css' %}">
  <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/theme-chalk.css' %}">
  <style>
    form.disabled{
      opacity: 0.75;
      pointer-events: none;
    }
  </style>
  {% block css_adicional %}{% endblock css_adicional %}
</head>
<body>
  {% block root %}
    {% include 'common/header.html' %}
    <div class="container is-fluid">
      {% block content %}
      <div class="notification">
        This container is <strong>centered</strong> on desktop.
      </div>
      {% endblock content %}
    </div>
    {% include 'common/footer.html' %}
  {% endblock root %}
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/vue.js' %}"></script>
  <script src="{% static 'js/lodash@1.8.3.js' %}"></script>
  <script src="{% static 'js/moment.min.js' %}"></script>
  <script src="{% static 'js/moment-with-locales.min.js' %}"></script>
  <script src="{% static 'js/axios@0.18.0.js' %}"></script>
  <script src="{% static 'js/sweetalert@2.1.0.js' %}"></script>
  <script src="{% static 'js/element-ui@2.4.7.js' %}"></script>
  <script src="{% static 'js/element-ui@locale-es.js' %}"></script>
  <script src="{% static 'system/components_bulma.js' %}"></script>
  <script>
    moment.locale('es');
    ELEMENT.locale(ELEMENT.lang.es)
    $('header a[href="'+window.location.pathname+'"]').parent().addClass('is-active');
    const csrfToken = "{{ csrf_token }}";
    var _axios = axios.create({
      // baseURL: 'https://some-domain.com/api/', 
      timeout: 5000,
      xsrfCookieName: 'csrftoken',
      xsrfHeaderName: 'X-CSRFToken',
      headers: {
        'X-Requested-with': 'XMLHttpRequest'
      }
    });
    Vue.prototype.$axios = _axios;
    Vue.prototype.$swal = swal;
  </script>
  {% block jsfinal %}{% endblock jsfinal %}
</body>
</html>

src/templates/common/footer.html
<footer class="footer">
	<div class="content has-text-centered">
		<p>
		<strong>MetriSalud</strong> por <a href="https://plus.google.com/u/0/+yelsonalfredochevarriashuamanccapu-developer">Yelson Chevarrias</a>. The source code is licensed
		<a href="https://opensource.org/licenses/GPL-2.0">GPL-2.0</a>. Source Code on <a href="https://github.com/ccapudev/metrisalud">GitHub</a>.
		</p>
	</div>
</footer>

src/templates/common/header.html
<header>
  <nav class="bd-tabs">
    <div class="tabs">
      <ul>
        <li>
          <a class="button is-text" href="/">
            <span class="icon">
              <i class="fa fa-home"></i>
            </span>
            <span>
              Inicio
            </span>
          </a>
        </li>
        <li>
          <a class="button is-text" href="{% url 'analisis:analisis_list' %}">
            <span class="icon">
              <i class="fa fa-plus"></i>
            </span>
            <span>
              Analisis
            </span>
          </a>
        </li>
        <li>
          <a class="button is-text" href="{% url 'analisis:resultados_list' %}">
            <span class="icon">
              <i class="fa fa-list"></i>
            </span>
            <span>
              Resultados
            </span>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</header>