src/apps/analisis_clinicos/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from apps.analisis_clinicos import views
from rest_framework_jwt.views import obtain_jwt_token

app_name = 'analisis_clinicos'

urlpatterns = [
    path('', views.AnalisisView.as_view(),
         name='analisis_list'),
    path('resultados/', views.ResultadosView.as_view(),
         name='resultados_list'),
    path('nuevo/<int:analisis_id>/', views.NewAnalisisView.as_view(),
         name='nuevo_resultado'),
]

src/metrisalud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include(
        ('django.contrib.auth.urls', 'auth'),
        namespace='auth'
    )),

    path('users/', include('apps.usuario.urls', namespace='user')),
    path('', include('apps.web.urls', namespace='web')),

    path('analisis/', include(
        'apps.analisis_clinicos.urls', namespace='analisis'
    )),
]

src/templates/analisis/analisis_item.html
<div class="card">
  <header class="card-header">
    <p class="card-header-title">
      {{ a.nombre }}
    </p>
    <a href="#" class="card-header-icon" aria-label="more options">
      <span class="icon">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </a>
  </header>
  <div class="card-content">
    <div class="content">
      este analisis se mide mediante {{ a.unidad_medida.simbolo }}
    </div>
  </div>
  <footer class="card-footer">
    <a href="#" class="card-footer-item">+1 </a>
    <a href="#" class="card-footer-item">Editar</a>
    <a href="{% url 'analisis:nuevo_resultado' a.id %}" class="card-footer-item">+ Resultado</a>
  </footer>
</div>

src/templates/analisis/lista_analisis.html
  {% extends 'common/base.html' %}
{% load static %}

{% block title %}Nueva medición{% endblock title %}
    
{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Listado de Análisis</h1>
    {% for a in analisis %}
      {% include 'analisis/analisis_item.html' %}
    {% endfor %}
  </div>
</section>
{% endblock content %}

src/templates/analisis/lista_resultados.html
  {% extends 'common/base.html' %}
{% load static %}

{% block title %}Nueva medición{% endblock title %}
    
{% block content %}
<section class="section">
  <div class="container" id="vContentMain">
    <h1 class="title">Listado de resultados</h1>
    <div class="columns" v-for="chunk, index in chunks" :key="index">
      <resultado-card v-for="resultado in chunk" :key="resultado.id" :resultado="resultado"></resultado-card>
    </div>
  </div>
</section>
{% endblock content %}
{% block jsfinal %}
<script type="text/javascript">
// (function(){
let main = new Vue({
  el: '#vContentMain',
  data: {
    resultados: []
  },
  methods: {
    getResultados(){
      this.$axios({
        url: '/analisis/resultados/',
        method: 'get',
      }).then(rsp => {
        this.resultados = rsp.data.result
        console.log(rsp.data)
      })
    }
  },
  computed: {
    chunks(){
      return _.chunk(this.resultados, 3)
    }
  },
  created(){
    this.getResultados()
  }
})
//})();
</script>
{% endblock jsfinal %}

src/templates/analisis/nuevo_resultado.html
{% extends 'common/base.html' %}
{% load static %}

{% block title %}Nueva medición{% endblock title %}
    
{% block content %}
<section class="section">
  <div class="container" id="vContentForm">
    <h1 class="title">Registrar resultado</h1>
    <form :class="{'disabled': sending}">
      <combo-usuario v-model="usuario_id"></combo-usuario>
      <controlador label="Fecha de examen">
        <el-date-picker
          v-model="fecha"
          type="datetime"
          format="dd/MM/yyyy HH:mm"
          value-format="dd/MM/yyyy HH:mm"
          placeholder="Seleccione fecha">
        </el-date-picker>
      </controlador>
      <combo-analisis v-model="analisis"></combo-analisis>
      <controlador v-if="analisis_type == 'numb'" label="Resultado">
        <el-input-number v-model="resultado" :min="1"></el-input-number>
      </controlador>
      <controlador v-else-if="analisis_type == 'bool'" label="Resultado">
        <select-boolean v-model="resultado"></select-boolean>
      </controlador>
      <div class="field is-grouped">
        <div class="control">
          <button class="button is-link" @click.prevent="guardar">Guardar</button>
        </div>
        <div class="control">
          <a href="{% url 'analisis:analisis_list' %}" class="button is-text">Cancelar</a>
        </div>
      </div>
    </form>
  </div>
</section>
{% endblock content %}

{% block jsfinal %}
<script type="text/javascript">
new Vue({
  el: '#vContentForm',
  data: {
    usuario_id: '',
    analisis: '',
    resultado: '',
    fecha: null,
    sending: false
  },
  methods: {
    guardar(){
      this.sending = true
      _axios({
        url: window.location.pathname,
        data: this.formData,
        method: 'post',
      }).then(rsp => {
        this.sending = false
        this.$swal("¡Listo!","Guardado con éxito", 'success')
      }).catch(err => {
        this.sending = false
        if(err.response.data.msg){
          this.$swal("¡Error!",err.response.data.msg, 'error')
        }
      })
    }
  },
  computed: {
    analisis_id(){
      return this.analisis ? this.analisis.value : null
    },
    analisis_type(){
      return this.analisis ? this.analisis.tr : null
    },
    formData(){
      let form = new FormData()
      form.append('analisis', this.analisis_id)
      form.append('paciente', this.usuario_id)
      form.append('fecha', this.fecha)
      form.append('analisis', this.analisis_id)
      form.append('valor_numerico', this.resultado)
      return form
    }
  },
  mounted(){
    // this.fecha = new Date()
  }
})
</script>
{% endblock jsfinal %}
  

src/templates/analisis/nuevo_resultado_success.html
{% extends 'common/base.html' %}
{% load static %}

{% block title %}Nueva medición{% endblock title %}
    
{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Resultado registrado exitosamente!</h1>
    <a class="button is-primary" href="{% url 'analisis:nuevo_resultado' analisis_id %}">
      <span class="icon">
        <i class="fa fa-plus"></i>
      </span>
      <span>
        Registrar nuevo resultado
      </span>
    </a>
    <a class="button is-info" href="{% url 'analisis:analisis_list' %}">
      <span class="icon">
        <i class="fa fa-angle-left"></i>
      </span>
      <span>
        Volver a lisado de analisis
      </span>
    </a>
  </div>
</section>
{% endblock content %}

src/templates/analisis/resultado_item.html
<div class="column is-one-third">
  <div class="card">
    <header class="card-header">
      <p class="card-header-title">
        {{ r.analisis_nombre }}
      </p>
      <a href="#" class="card-header-icon" aria-label="more options">
        <span class="icon">
          <i class="fas fa-angle-down" aria-hidden="true"></i>
        </span>
      </a>
    </header>
    <div class="card-content">
      <div class="content">
        realizado {{ r.fecha }} 
      </div>
    </div>
    <footer class="card-footer">
      <a class="card-footer-item">Unidad: {{ r.simbolo }}</a>
      <a class="card-footer-item">{{ r.valor }}</a>
    </footer>
  </div>
</div>